[lib]
proc-macro = true

[package]
name = "struct-record"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-expand = "1.0.121"
convert_case = "0.11.0"
paste = "1.0.15"
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = "2.0.117"
